// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SASA.PayNow.SampleClient.RazorP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181119124511_EditModel_PayNowObject_AddedProperties")]
    partial class EditModel_PayNowObject_AddedProperties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SASA.PayNow.SampleClient.RazorP.Models.PayNowObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JSDictionay");

                    b.Property<int>("PaymentStatus");

                    b.Property<string>("PollUrl");

                    b.Property<string>("Reference");

                    b.Property<decimal>("Total");

                    b.HasKey("Id");

                    b.ToTable("PayNowObject");
                });
#pragma warning restore 612, 618
        }
    }
}
